modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/xs_267/BalancedFlight/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/xs_267/BalancedFlight"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "create"
    type = "required"
    versionRange = "${create_version_range}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "curios"
    type = "required"
    versionRange = "${curios_version_range}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "geckolib"
    type = "required"
    versionRange = "${geckolib_version_range}"
    ordering = "AFTER"
    side = "BOTH"
